# Import modules...
from modules.charts import createChart
from modules.excel import automateToExcel
from modules.word import createWordFile
from modules.webscraper import scrapeUrl
from modules.statistics import mean, median, mode
from modules.powerpoint import createTitleSlide, createContentSlide

# Run Unit Test here...

# Test 1...
print("Me: Generate a bar graph based on the given data")
chart_confirmed = createChart(title="Generated by Agentic AI", x="Cars", y="Revenue", kind="bar")
print(chart_confirmed)

# Test 2...
print("Me: Generate a spreadsheet based on the given data")
book_confirmed = automateToExcel()
print(book_confirmed)

# Test 3...
print("Me: Generate a word document based on the given data")
doc_confirmed = createWordFile()
print(doc_confirmed)

# Test 4...
print("Me: Fetch some data based on the given url")
data_confirmed = scrapeUrl("https://youtube.com")
print(data_confirmed)

# Test 5...
numbers = [10, 20, 35, 15, 40]
print("Me: On the basis on the given data, find Mean, Median, and Mode respectively.")
m1 = mean(numbers)
m2 = median(numbers)
m3 = mode(numbers)
print(m1, m2, m3)

# Test 6...
print("Me: Generate a title slide based on given data")
ppt_confirmed = createTitleSlide()
print(ppt_confirmed)

# Test 7...
print("Me: Generate a content slide in the same pptx file from before...")
slide_confirmed = createContentSlide()
print(slide_confirmed)